export const actions = {
  profile: {
    DATA_FATCHING: "PROFILE_DATA_FATCHING",
    DATA_FATCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "PROFILE_USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
  post: {
    DATA_FATCHING: "POST_DATA_FATCHING",
    DATA_FATCHED: "POST_DATA_FACHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_EDITRD: "POST_DATA_EDITED",
    POST_DELETED: "POST_DATA_DELETED",
    POST_LINKED: "POST_DATA_LIKED",
    POST_COMMENT: "POST_DATA_COMMENT",
  },
};
